name: 🐛 Bug Report
description: Something is wrong with Remix.
labels:
  - "bug:unverified"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping to improve Remix!

        The fastest way to get your bug fixed is to provide the best reproduction you can.

        🏆 The most helpful option is to use our _bug report integration test_ template:

        1. [Fork `remix-run/remix`](https://github.com/remix-run/remix/fork)
        2. Open [`integration/bug-report-test.ts`](https://github.com/remix-run/remix/blob/dev/integration/bug-report-test.ts) in your editor
        3. Follow the instructions and submit a pull request with a failing bug report test!

        If you'd rather open a GitHub issue, here are your other options for sharing a reproduction (ordered from most helpful to least):

        - 🥇 Link to a [StackBlitz](https://stackblitz.com/?starters=fullstack) environment
        - 🥈 Link to a GitHub repository
        - 🥉 Description of project including template, `remix.config.js`, `package.json` scripts, etc.

  - type: textarea
    id: reproduction
    attributes:
      label: reproduction
      description: Link to reproduction and steps to reproduce the behavior
      placeholder: Go to https://stackblitz.com/edit/remix-run-remix-amhhla?file=README.md and click the "Submit" button
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --npmPackages '{vite,@remix-run/*}' --binaries --browsers`
      render: shell
      placeholder: System, Binaries, Browsers
    validations:
      required: true
  - type: dropdown
    id: package-manager
    attributes:
      label: Used Package Manager
      description: Select the used package manager
      options:
        - npm
        - yarn
        - pnpm
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
