name: Format with Nano Staged

on:
  push:
    branches:
      - main
      - dev

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.FORMAT_PAT }}

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Format with Nano Staged
        run: |
          if [ ${{ github.event_name == 'push' }} ]; then
            git fetch origin ${{ github.event.before }}
            npx nano-staged --diff ${{ github.event.before }} -c ./.format.js
          fi
