name: 📦 Merged PR

on:
  pull_request:
    types: [closed]
    branches:
      - dev

permissions:
  pull-requests: write

jobs:
  merged:
    name: Add label to merged PR
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            packages:
              - 'packages/**'

      - uses: actions-ecosystem/action-add-labels@v1
        if: steps.changes.outputs.packages == 'true'
        with:
          labels: "awaiting release"
          number: ${{ github.event.pull_request.number }}
          repo: ${{ github.repository }}
