name: 🥺 No Response

on:
  schedule:
    # Schedule for five minutes after the hour, every hour
    - cron: "5 * * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    if: github.repository == 'remix-run/remix'
    runs-on: ubuntu-latest
    steps:
      - name: 🥺 Handle Ghosting
        uses: actions/stale@v8
        with:
          close-issue-message: >
            This issue has been automatically closed because we didn't hear
            anything from the original author after the previous notice.
          close-pr-message: >
            This PR has been automatically closed because we didn't hear
            anything from the original author after the previous notice.
          days-before-close: 10
          days-before-stale: -1
          only-labels: needs-response
