name: 📝 Comment on Release

on:
  workflow_call:

jobs:
  comment:
    name: 📝 Comment on related issues and pull requests
    if: github.repository == 'remix-run/remix'
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 📝 Comment on issues
        uses: mcansh/release-comment-action@v0.1.3
        env:
          DIRECTORY_TO_CHECK: "./packages"
          PACKAGE_VERSION_TO_FOLLOW: "remix"
          GITHUB_REPOSITORY: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
