name: test

on:
  push:
    branches:
      - main
      - dev
      - release/*
    tags-ignore:
      - v*
    paths-ignore:
      - "docs/**"
      - "**/README.md"
  pull_request: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # TODO: Fix cross-env issues in Jest before enabling
          # - windows-latest
    steps:
      # https://github.com/actions/virtual-environments/issues/1187
      - name: prep windows network
        run: Disable-NetAdapterChecksumOffload -Name * -TcpIPv4 -UdpIPv4 -TcpIPv6 -UdpIPv6
        if: ${{ matrix.settings.host == 'windows-latest' }}
      
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile --network-timeout 1000000

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
